const HeroSliderStyles = {
  carouselContainer: {
    margin: 0,
    padding: 0,
    boxSizing: "border-box",
    height: "100vh",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
  },
  navbarContainer: {
    width: "100%",
    height: "100px",
    padding: "21px 20px",
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 2,
  },
  slideContainer: {
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative",
    zIndex: 1,
  },
  slideBackground: {
    height: "100%",
    width: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    backgroundPosition: "center",
    backgroundSize: "cover",

    "-webkit-animation": "kenburns-top 2s ease-out both",
    animation: "kenburns-top 2s ease-out both",
  },

  "@-webkit-keyframes kenburns-top": {
    " 0% ": {
      "-webkit-transform": "scale(1) translateY(0)",
      transform: "scale(1) translateY(0)",
      "-webkit-transform-origin": "50% 16%",
      "transform-origin": "50% 16%",
    },
    " 100%": {
      "-webkit-transform": "scale(1.25) translateY(-15px)",
      transform: "scale(1.25) translateY(-15px)",
      "-webkit-transform-origin": "top",
      "transform-origin": "top",
    },
  },
  "@keyframes kenburns-top": {
    "0%": {
      "-webkit-transform": "scale(1) translateY(0)",
      transform: "scale(1) translateY(0)",
      "-webkit-transform-origin": "50% 16%",
      "transform-origin": "50% 16%",
    },
    "100%": {
      "-webkit-transform": "scale(1.25) translateY(-15px)",
      transform: "scale(1.25) translateY(-15px)",
      "-webkit-transform-origin": "top",
      "transform-origin": "top",
    },
  },
  slideContent: {
    position: "absolute",
    top: " 50%",
    left: "0%",
    transform: "translateY(-50%)",
    zIndex: 2,
    color: "#fff",
    textShadow: "1px 1px 5px rgba(0,0,0,0.6)",
    width: "35%",
    marginLeft: "7%",
  },
  slideTitle: {
    marginTop: "20px",
    color: "#EEF4F9",
    fontSize: "64px",
    fontWeight: 400,
    textTransform: "capitalize",
    lineHeight: "100%",
  },
  slideSubtitle: {
    color: "#EEF4F9",
    fontSize: "16px",
    fontWeight: 400,
    textTransform: "capitalize",
  },
  navigation: {
    width: "25%",
    marginLeft: "7%",
    marginBottom: "4%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    position: "absolute",
    bottom: 0,
    left: 0,
    zIndex: 2,
  },
  navButton: {
    padding: "10px 20px",
    backgroundColor: "#fff",
    color: "#000",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "18px",
    fontWeight: 700,
    boxShadow: "1px 1px 5px rgba(0,0,0,0.5)",
    transition: "background-color 0.3s ease-in-out, color 0.3s ease-in-out",
  },
  thumbnailContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid #EEF4F9",
  },
  thumbnail: {
    width: "65px",
    height: "65px",
    margin: "12px",
    overflow: "hidden",
    cursor: "pointer",
    transition: "border-color 0.3s ease-in-out",
    position: "relative",
  },
  thumbnailImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  thumbnailText: {
    position: "absolute",
    color: "#EEF4F9",
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: "110%",
    cursor: "pointer",
  },
  spanText: { color: "white", fontSize: "16px", fontWeight: 400 },
};

export default HeroSliderStyles;
